version: '3.9'

services:
  api:
    build:
      context: ./docker/php-fpm/prod
    volumes:
      - ./api:/var/www/api
    restart: always

  nginx:
    image: nginx:stable
    volumes:
      - ./docker/nginx/prod/default.conf:/etc/nginx/conf.d/default.conf
      - ./api:/var/www/api
    ports:
      - 80:80
    restart: always

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_value:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: goodlavka_com
      MYSQL_USER: gladkix
      MYSQL_PASSWORD: 666666qq
    restart: always

  app:
    build:
      context: ./docker/app
    volumes:
      - ./app:/var/www/app

  admin:
    build:
      context: ./docker/admin/prod
    volumes:
      - ./admin:/var/www/admin


volumes:
  mysql_value: